In [1]:
import torch

In [2]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape 

a.reshape(2,4,2) # this create the view ie no impact on the original array


tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
a # so a is not changed 


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# flatten 

a.flatten() # this flattens to one d tensors

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
b = torch.rand(2,3,5)
b

tensor([[[0.8622, 0.7663, 0.9196, 0.9477, 0.7844],
         [0.1759, 0.5374, 0.0308, 0.6002, 0.6513],
         [0.4814, 0.0357, 0.3408, 0.6425, 0.0617]],

        [[0.3677, 0.5756, 0.0276, 0.3409, 0.4708],
         [0.5009, 0.7561, 0.9104, 0.8044, 0.6344],
         [0.6264, 0.4204, 0.4473, 0.7768, 0.2851]]])

In [ ]:
# permutations 

b.permute(2,0,1) # this rearrange as 2 to first, 0 to middle and 1 at the end 

# this creates b.reshape(5,3,2)

tensor([[[0.8622, 0.1759, 0.4814],
         [0.3677, 0.5009, 0.6264]],

        [[0.7663, 0.5374, 0.0357],
         [0.5756, 0.7561, 0.4204]],

        [[0.9196, 0.0308, 0.3408],
         [0.0276, 0.9104, 0.4473]],

        [[0.9477, 0.6002, 0.6425],
         [0.3409, 0.8044, 0.7768]],

        [[0.7844, 0.6513, 0.0617],
         [0.4708, 0.6344, 0.2851]]])

In [ ]:
b.reshape(5,3,2) # as we can see it is same as permute one . 

tensor([[[0.8622, 0.7663],
         [0.9196, 0.9477],
         [0.7844, 0.1759]],

        [[0.5374, 0.0308],
         [0.6002, 0.6513],
         [0.4814, 0.0357]],

        [[0.3408, 0.6425],
         [0.0617, 0.3677],
         [0.5756, 0.0276]],

        [[0.3409, 0.4708],
         [0.5009, 0.7561],
         [0.9104, 0.8044]],

        [[0.6344, 0.6264],
         [0.4204, 0.4473],
         [0.7768, 0.2851]]])

In [ ]:
# unsqueeze
# image size used in CNN
c= torch.rand(226,226,3)
c


tensor([[[0.2717, 0.1682, 0.1019],
         [0.0962, 0.4366, 0.3318],
         [0.4278, 0.4044, 0.4840],
         ...,
         [0.8752, 0.9433, 0.8275],
         [0.0282, 0.6887, 0.1614],
         [0.9790, 0.2939, 0.3473]],

        [[0.7810, 0.0467, 0.3390],
         [0.7067, 0.4575, 0.0379],
         [0.8269, 0.3248, 0.6313],
         ...,
         [0.3610, 0.9572, 0.0043],
         [0.1509, 0.1060, 0.7234],
         [0.8123, 0.5019, 0.8186]],

        [[0.7234, 0.4770, 0.5801],
         [0.5475, 0.8543, 0.8895],
         [0.6462, 0.7228, 0.1567],
         ...,
         [0.6946, 0.2125, 0.7419],
         [0.4642, 0.9421, 0.2069],
         [0.7313, 0.4750, 0.7996]],

        ...,

        [[0.5098, 0.9297, 0.0641],
         [0.6846, 0.0612, 0.9399],
         [0.2598, 0.5747, 0.6285],
         ...,
         [0.7654, 0.6199, 0.3774],
         [0.4797, 0.9005, 0.9045],
         [0.3364, 0.6511, 0.5007]],

        [[0.6606, 0.0389, 0.3592],
         [0.3857, 0.6553, 0.7051],
         [0.

In [ ]:
c.unsqueeze(0).shape # this add new tensors at the 1st dimensions 

torch.Size([1, 226, 226, 3])

In [17]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [ ]:
# squeeze 

d = torch.rand(1,20)
d.squeeze(0).shape # this removes the first dimenstion ie 1 from here 

torch.Size([20])