Tensor Operations on GPU

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
device = torch.device('cuda')


#creating a new tensor on GPU

In [4]:
torch.rand((2,4),device=device)

tensor([[0.5863, 0.9593, 0.0011, 0.5695],
        [0.1981, 0.0673, 0.6700, 0.1847]], device='cuda:0')

In [5]:
# movind an existing tensor in GPU
a= torch.rand(2,3)
a

tensor([[0.5648, 0.0521, 0.3222],
        [0.1713, 0.1971, 0.7765]])

In [ ]:
b = a.to(device) # transferring to gpu

In [ ]:
b + 4 # now this will run of the gpu 

tensor([[4.5648, 4.0521, 4.3222],
        [4.1713, 4.1971, 4.7765]], device='cuda:0')

Testing CPU VS GPU


In [9]:
import time

# definin the large size of matrices
size = 10000

#create random matrices on CPU

matrix_cpu1= torch.randn(size,size)
matrix_cpu2= torch.randn(size,size)

# measure time
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on Cpu: {cpu_time:.4f}seconds")

#create random matrices on GPU

matrix_gpu1= matrix_cpu1.to('cuda')

matrix_gpu2= matrix_cpu2.to('cuda')

# measure time
start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f}seconds")
print('\n Speedup (CPU time/GPU time):', cpu_time/gpu_time)

Time on Cpu: 4.5546seconds
Time on GPU: 0.0107seconds

 Speedup (CPU time/GPU time): 425.6277209633937
