https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [6]:
import torch
print(torch.__version__)

2.12.0+cu132


In [7]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not avialable using CPU")

GPU is available
Using GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU


1. Creating a Tensor

In [8]:
# creating empty tensors
a=torch.empty(2,3)

# checking the type
type(a)


torch.Tensor

In [9]:
#using zeros
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
#using ones
torch.ones(2,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
#using rand
torch.rand(2,3) #gives float between 0 and 1

tensor([[0.3686, 0.7878, 0.9929],
        [0.5825, 0.2000, 0.0601]])

In [12]:
#manual seed
torch.manual_seed(100)
torch.rand(3,5)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876, 0.4183]])

In [13]:
# As we can now use same seed to generate the same random tensors we have generated. It is very useful for the consitensy purposes
torch.manual_seed(100)
torch.rand(3,5)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876, 0.4183]])

In [14]:
#Other ways

#arrange:
print("Using arange :" ,torch.arange(0,10,2))

#using linspace:
print("Using linspace: ", torch.linspace(0,10,10))

#Using eye 
print("Using eye :",torch.eye(5))

#Using full 
print("Using full : ",torch.full((3,3),5))


Using arange : tensor([0, 2, 4, 6, 8])
Using linspace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye : tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


1.Tensor Shapes

In [15]:
x= torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
print(x.shape)

torch.Size([2, 3])


In [17]:
torch.empty_like(x) # thiese like function gives an tensor with the same shape as the input which is x here. 


tensor([[    110199831375773,                   0,     110224405676760],
        [ 289355176546926592, 4596373635383427072, 4588815575274225664]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784]])

3.Tensor Data Types:

In [21]:
#find the data types.
x.dtype

torch.int64

In [22]:
# we can assign the specific data types 
torch.tensor([1.0,1.3,4.0],dtype=torch.int32)


tensor([1, 1, 4], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# using to() can convert the dtype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations

1.Scaler operations

In [25]:
x = torch.rand(2,2)
x

tensor([[0.8238, 0.5557],
        [0.9770, 0.4440]])

In [26]:
# Addition
print(x+2)
# Substraction
print(x-2)
# Multiplications

print(x*2)
# Division
print(x/3)
# Int Division
print((x*200)//3)
# mod
print(((x*100)//3)%2)
# power
print(x**2)

tensor([[2.8238, 2.5557],
        [2.9770, 2.4440]])
tensor([[-1.1762, -1.4443],
        [-1.0230, -1.5560]])
tensor([[1.6477, 1.1115],
        [1.9540, 0.8880]])
tensor([[0.2746, 0.1852],
        [0.3257, 0.1480]])
tensor([[54., 37.],
        [65., 29.]])
tensor([[1., 0.],
        [0., 0.]])
tensor([[0.6787, 0.3089],
        [0.9546, 0.1972]])


2.Element wise operation


In [27]:
a=torch.rand(2,4)
b= torch.rand(2,4)

print(a)
print(b)



tensor([[0.9478, 0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472, 0.7909]])
tensor([[0.4235, 0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902, 0.5163]])


In [28]:
# Addition
print(a+b)
# Substraction
print(a-b)
# Multiplications

print(a*b)
# Division
print(a/b)
# Int Division
print(a//b)
# mod
print(a%b)
# power
print(a**b)

tensor([[1.3713, 0.7614, 0.7101, 1.1961],
        [1.4067, 0.6906, 1.1374, 1.3072]])
tensor([[ 0.5244,  0.7276,  0.2683, -0.7110],
        [-0.0061,  0.3648, -0.6430,  0.2746]])
tensor([[0.4014, 0.0126, 0.1081, 0.2313],
        [0.4947, 0.0859, 0.2200, 0.4083]])
tensor([[ 2.2382, 44.0545,  2.2146,  0.2544],
        [ 0.9914,  3.2398,  0.2777,  1.5319]])
tensor([[ 2., 44.,  2.,  0.],
        [ 0.,  3.,  0.,  1.]])
tensor([[0.1009, 0.0009, 0.0474, 0.2426],
        [0.7003, 0.0391, 0.2472, 0.2746]])
tensor([[0.9776, 0.9950, 0.8539, 0.2591],
        [0.7775, 0.9011, 0.2882, 0.8859]])


In [29]:
c= torch.tensor([1.9,4.5,6.4,3.4])
d= torch.tensor([1.9,4.3,6.5,8.9])
print(c,d)

tensor([1.9000, 4.5000, 6.4000, 3.4000]) tensor([1.9000, 4.3000, 6.5000, 8.9000])


In [30]:
# abs for absolute
torch.abs(c)

tensor([1.9000, 4.5000, 6.4000, 3.4000])

In [31]:
#for negative 
torch.neg(c)

tensor([-1.9000, -4.5000, -6.4000, -3.4000])

In [32]:
#round
torch.round(d)

tensor([2., 4., 6., 9.])

In [33]:
#ceil
e= torch.tensor([1.4,3.5,4.8])
f= torch.tensor([1.4,3.5,4.8])
torch.ceil(e)

tensor([2., 4., 5.])

In [34]:
#floor
torch.floor(f)

tensor([1., 3., 4.])

In [35]:
# clamp
g= torch.tensor([1.9,4.3,6.5,8.9])
torch.clamp(g, min=2, max=8)

tensor([2.0000, 4.3000, 6.5000, 8.0000])

3.Reduction operation


In [36]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 5., 9.],
        [9., 7., 5.]])

In [37]:
#sum
print(torch.sum(e))

#sum along columns

print(torch.sum(e,dim=0))

# sum along rows
print(torch.sum(e,dim=1))

tensor(42.)
tensor([16., 12., 14.])
tensor([21., 21.])


In [38]:
# mean
print(torch.mean(e))
# mean along col
print(torch.mean(e, dim=0))
# mean along row
print(torch.mean(e, dim=1))

tensor(7.)
tensor([8., 6., 7.])
tensor([7., 7.])


In [39]:
# median
torch.median(e)

tensor(7.)

In [40]:
#mode
f=torch.tensor([1,2,2,3,2,3,1])
torch.mode(f)

torch.return_types.mode(
values=tensor(2),
indices=tensor(4))

In [41]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(5.)


In [42]:
e

tensor([[7., 5., 9.],
        [9., 7., 5.]])

In [43]:
# product
torch.prod(e)

tensor(99225.)

In [44]:
# standard deviation
torch.std(e)

tensor(1.7889)

In [45]:
# variance
torch.var(e)

tensor(3.2000)

In [46]:
g=torch.tensor([[1,2,3,4,5],[7,8,9,10,11]])
g

tensor([[ 1,  2,  3,  4,  5],
        [ 7,  8,  9, 10, 11]])

In [47]:
# argmax
torch.argmax(g) # give index of the mazimum value 

tensor(9)

In [48]:
# argmin
torch.argmin(g) # gives the incidce ot which the minimum value is locatied

tensor(0)

4. Matrix operations

In [49]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [50]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[137, 181],
        [111, 133]])

In [51]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [52]:
# transpose
torch.transpose(f, 0, 1)

tensor([[9, 7],
        [8, 9],
        [9, 2]])

In [53]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 5., 5.],
        [0., 4., 3.],
        [8., 8., 3.]])

In [54]:
# determinant
torch.det(h)

tensor(-52.0000)

In [55]:
# inverse
torch.inverse(h)

tensor([[ 0.2308, -0.4808,  0.0962],
        [-0.4615,  0.7115,  0.0577],
        [ 0.6154, -0.6154, -0.0769]])

5. Comparison operations

In [56]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 5, 0],
        [6, 4, 0]])
tensor([[8, 4, 7],
        [2, 3, 8]])


In [57]:
# greater than
print(i > j)
# less than
print(i < j)
# equal to
print(i == j)
# not equal to
print(i !=j )
# greater than equal to
print(i>=j)
# less than equal to
print(i<=j)

tensor([[False,  True, False],
        [ True,  True, False]])
tensor([[ True, False,  True],
        [False, False,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False,  True, False],
        [ True,  True, False]])
tensor([[ True, False,  True],
        [False, False,  True]])


### 6. Special functions


In [58]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 6., 2.],
        [9., 5., 0.]])

In [59]:
#log
torch.log(k)

tensor([[1.6094, 1.7918, 0.6931],
        [2.1972, 1.6094,   -inf]])

In [60]:
#exponential
torch.exp(k)

tensor([[1.4841e+02, 4.0343e+02, 7.3891e+00],
        [8.1031e+03, 1.4841e+02, 1.0000e+00]])

In [61]:
# square root
torch.sqrt(k)

tensor([[2.2361, 2.4495, 1.4142],
        [3.0000, 2.2361, 0.0000]])

In [62]:
# sigmoid

torch.sigmoid(k)

tensor([[0.9933, 0.9975, 0.8808],
        [0.9999, 0.9933, 0.5000]])

In [63]:
#relu

torch.relu(k)

tensor([[5., 6., 2.],
        [9., 5., 0.]])

Inplace Operations

In [64]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2324, 0.9141, 0.7668],
        [0.1659, 0.4393, 0.2243]])
tensor([[0.8935, 0.0497, 0.1780],
        [0.3011, 0.1893, 0.9186]])


In [65]:
m.add_(n)

tensor([[1.1259, 0.9638, 0.9448],
        [0.4670, 0.6286, 1.1429]])

In [66]:
m

tensor([[1.1259, 0.9638, 0.9448],
        [0.4670, 0.6286, 1.1429]])

In [68]:
print(n)

tensor([[0.8935, 0.0497, 0.1780],
        [0.3011, 0.1893, 0.9186]])


In [69]:
torch.relu(m)

tensor([[1.1259, 0.9638, 0.9448],
        [0.4670, 0.6286, 1.1429]])

In [ ]:
m.relu_() # so this relu is also inplace operations

tensor([[1.1259, 0.9638, 0.9448],
        [0.4670, 0.6286, 1.1429]])

In [74]:
print(m)

n

tensor([[1.1259, 0.9638, 0.9448],
        [0.4670, 0.6286, 1.1429]])


tensor([[0.8935, 0.0497, 0.1780],
        [0.3011, 0.1893, 0.9186]])

Copying a Tensor

In [75]:
a = torch.rand(2,3)
a

tensor([[0.2131, 0.3957, 0.6017],
        [0.4234, 0.5224, 0.4175]])

In [76]:
b=a

this create the like view in numpy. Ie original tensor will be affected when chnages made to b and vice versa . 

In [77]:
b

tensor([[0.2131, 0.3957, 0.6017],
        [0.4234, 0.5224, 0.4175]])

In [ ]:
a[0][0] = 0 # changin value in a 
a

tensor([[0.0000, 0.3957, 0.6017],
        [0.4234, 0.5224, 0.4175]])

In [ ]:
b # note b also changed so original and copy are linked 

tensor([[0.0000, 0.3957, 0.6017],
        [0.4234, 0.5224, 0.4175]])

In [ ]:
id(b) # they both a and b are pointing in same memory locationas id is same 

138101726617552

In [82]:
id(a)

138101726617552

So for copying that ie cloning so that original tensor is not affected we use clone() method 

In [84]:
c=a.clone()

In [85]:
c

tensor([[0.0000, 0.3957, 0.6017],
        [0.4234, 0.5224, 0.4175]])

In [86]:
a[0][0]=10
a

tensor([[10.0000,  0.3957,  0.6017],
        [ 0.4234,  0.5224,  0.4175]])

In [87]:
c

tensor([[0.0000, 0.3957, 0.6017],
        [0.4234, 0.5224, 0.4175]])

In [88]:
print(id(a))
print(id(c))

138101726617552
138101726773328
