In [5]:
#create model class
import torch
import torch.nn as nn
# we are implementing simple model with 1 neuron 5 weights and 1 bias . It is binary classification problem 
# we are improving using hidden layer of relu then applying the sigmoid 
class Model(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features,3)  # first layer
        self.relu = nn.ReLU()  #hidden using relu
        self.linear2 = nn.Linear(3,1)  # takes three weights/inputs gives 1 using sigmoid activation function 
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):

        out = self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out= self.sigmoid(out)

        return out
    

In [6]:
#create dataset 

features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass

# model.forward(features) pytorch has implemented autocall of the forward method . so if we call object as the function the forward of the class auto runs 

model(features)

tensor([[0.4268],
        [0.4300],
        [0.4303],
        [0.4298],
        [0.4370],
        [0.4296],
        [0.4247],
        [0.4278],
        [0.4286],
        [0.4311]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight # we get 15 weights 


Parameter containing:
tensor([[ 0.3070,  0.2183,  0.0311,  0.1223,  0.3954],
        [-0.3166, -0.2521, -0.4216,  0.1265, -0.0310],
        [-0.1459, -0.3350,  0.0583,  0.3809,  0.2287]], requires_grad=True)

In [ ]:
model.linear2.weight # we get 3 weights 

Parameter containing:
tensor([[ 0.1162,  0.0384, -0.0638]], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

# we can see for linear1 18 params ie 15 wieghts 3 bias 
# and for linear two  there 4 ie 3 weights 1 bias 

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00