In [ ]:
import torch


# Clearing gradient

In [8]:
x=torch.rand((1),requires_grad=True)
x

tensor([0.1028], requires_grad=True)

In [12]:
y=x**2
y

tensor([0.0106], grad_fn=<PowBackward0>)

In [13]:
y.backward()

x.grad
# tensor([0.2056])
# when we run another pass 
# tensor([0.4112])

tensor([0.4112])

So when we run the multiple pass the gradience doesnot clears itself . so it will add up to the previous gradience .which is not desirable so we need to clear the gradient before re running the new pass 

In [ ]:
x.grad.zero_() # this will clear the gradience for next epoch 

# Disable Gradient Tracking 

### Sometimes we donot need to calculate the gradient . For ex when the NN is trained and we want to use it for prediction. During the prediction we donot need the gradient tracking as we just neet the forward pass. As backward pass willl not run anyway/. T his is done because for the big NN this gradient tracking comsumes the memory. so to preserve that we will stop this tracking during the use for predictions 

In [14]:
x= torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [15]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [16]:
y.backward()

In [17]:
x.grad

tensor(4.)

### so for ex here the training ends . So now we need to stop tracking 

### option 1 - requires_grad_(False)
### option 2 - detach()
### option 3 - torch.no_grad()

## Method 1 : 

In [19]:
x.requires_grad_(False)

tensor(2.)

In [20]:
x # now we donot see the tracking at op 

tensor(2.)

In [21]:
y = x**2 
y

tensor(4.)

In [ ]:
y.backward() # this will give error as tracking is stopped. 

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

## Method 2:

In [30]:
x= torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [34]:
z=x.detach()
z

tensor(2.)

In [35]:
y = x** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [36]:
y1= z**2 
y1

tensor(4.)

In [37]:
y.backward()

In [ ]:
y1.backward() # this will ntot work as z is detached from the x 

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

## Method 3 : 

In [39]:
x= torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
with torch.no_grad():
    y = x ** 2

# y = x ** 2 # with this the backtracking is on 
# now y is not tracking 

In [43]:
y.backward()